platform :ios, '7.0'

# pod 'jre_emul', :git => '../../..'
# xcconfig's HEADER_SEARCH_PATHS won't work in local path mode.
# pod 'jre_emul', :path => '../../..'

pod 'simple', :path => '..'
# Next line needs to manually import generated sources to Xcode.
# podspec :path => '../simple.podspec'