platform :ios, '7.0'

pod 'J2ObjC', :git => '/Users/retechretech/dev/tools/lib/j2objc', :branch=>'lib'
# xcconfig's HEADER_SEARCH_PATHS won't work in local path mode.
# pod 'J2ObjC', :path => '../../../J2ObjC.podspec'

pod 'simple', :path => '..'
# Next line needs to manually import generated sources to Xcode.
# podspec :path => '../simple.podspec'

link_with ['simple', 'demo']