platform :ios, '7.0'

# podspec :path => '../simple.podspec'
pod 'simple', :path => '..'
# To use the master branch of the repo:
pod 'jre_emul', :git => 'https://github.com/goodow/j2objc.git'
# Using the files from a local path.
# pod 'jre_emul', :path => '../../..'